### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by Jonny-Cho** [Jonny-Cho/commerce-user-ms#1]
![image](https://user-images.githubusercontent.com/24591642/149336780-f5460cfe-ee57-41a6-b7cb-4f0ea51fa975.png)

@EnableDiscoveryClient 추가

application.yml
```
server:
  port: 0
spring:
  application:
    name: user-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
```
